Dice with Death Game  Issue#34
World-of-ML/Play-With-Python pull request #115
Opened 2022-12-10 03:43 UTC by devika-singh

# Pull Request for Play With Python 💡

## Issue Title : Dice with Death Game

- **Info about the related issue (Aim of the project)** : Implement the Dice with Death Game using Python
- **Name:** Devika Singh
- **GitHub ID:** devika-singh
- **Email ID:** devikas.iitg@gmail.com
- **Idenitfy yourself: (Mention in which program you are contributing in.)** CODEPEAK 2022

Closes: #34 

### Describe the add-ons or changes you've made 📃
I have added the game Dice with Death folder and its game itself, with main.py, Images folder and images of game screens and the README.md
Used https://www.youtube.com/watch?v=ex24RomyPXk to understand rules of the game.

## Type of change ☑️

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
I entered yes in continue playing till all test cases had been encountered

## Checklist: ☑️
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

2022-12-10 03:52 UTC, abhisheks008 requested changes
Can you upgrade the user interaction technique from CLI to GUI. It'll be better for the users to have more interaction with the game.
@devika-singh

2022-12-10 19:37 UTC, devika-singh commented
@abhisheks008  I made the changes pls re-review it

2022-12-19 15:22 UTC, abhisheks008 requested changes

2022-12-19 15:22 UTC, abhisheks008 commented on Dice with Death/main.pyw
> +# importing the random module
The extension will be, `.py` instead of `.pyw`.

2022-12-19 15:24 UTC, abhisheks008 approved these changes
Your PR is approved and ready to be merged.
@devika-singh

2022-12-19 15:25 UTC, merged