Create clock.py
World-of-ML/Play-With-Python pull request #121
Opened 2022-12-11 14:32 UTC by nik132-eng

# Pull Request for Play With Python 💡

## Issue Title : Digital Clock #94 

- **Info about the related issue (Aim of the project)** : Show time in digital clock
- **Name:** Nikunj Rohit
- **GitHub ID:** nik132-eng
- **Email ID:** 19itnik132@ldce.ac.in
- **Idenitfy yourself: (Mention in which program you are contributing in.)** 

Closes: #94 

### Describe the add-ons or changes you've made 📃

Give a clear description of what have you added or modifications made

## Type of change ☑️

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested? ⚙️

Describe how it has been tested
Describe how have you verified the changes made

## Checklist: ☑️

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

2022-12-13 04:44 UTC, nik132-eng commented
can anyone please check this PR?

2022-12-14 13:50 UTC, joleyasarthak commented
Hey @nik132-eng, as a past contributor of this repo, I suggest you to please make a folder, and add your work there, in a proper structure. Please refer the [This](https://github.com/World-of-ML/Play-With-Python#structure-of-the-projects-), as to how you should structure. Hope it helps.

2022-12-15 16:36 UTC, nik132-eng commented
ok thank you I will doing this

2022-12-17 13:29 UTC, abhisheks008 requested changes
Please follow the project structure and add files accordingly.
@nik132-eng

2022-12-19 04:12 UTC, abhisheks008 commented
Project structure will be like this,
```
Digital Clock
|-- Images
    |-- image1.png
    |-- image2.png
|-- main.py
|-- README.md
|-- requirements.txt
```

2022-12-19 14:07 UTC, abhisheks008 requested changes
1. Add the **Images** folder.
2. Rename the `readme_template.md` file as `README.md`.
3. Add the demonstration images inside the README.md file under the Demonstration heading. To add the images in the README.md file, you can use this syntax, `![](image url fetched from the Images folder)`.

2022-12-21 10:32 UTC, nik132-eng commented
Now this is Ok?

2022-12-21 13:47 UTC, abhisheks008 requested changes

2022-12-21 13:47 UTC, abhisheks008 commented on Digital clock/readme.md
> +
Please add the demonstration images here,
syntax for adding images, `![image name](image URL fetched from the Images folder)`

2022-12-23 04:10 UTC, abhisheks008 approved these changes
LGTM! Your PR is approved and ready to be merged.
@nik132-eng

2022-12-23 04:12 UTC, merged